services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - VERSION=docker
      - PLEX_CLAIM=claim-cNEK_sAZtHzSCna56f-Y
    volumes:
      - ./config/plex:/config
      - ./media/movies:/movies
      - ./media/tv:/tv
    ports:
      - 32400:32400
    networks:
      - media_net
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config/radarr:/config
      - ./media/movies:/movies
      - ./downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - media_net
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config/sonarr:/config
      - ./media/tv:/tv
      - ./downloads:/downloads
    ports:
      - 8989:8989
    networks:
      - media_net
    restart: unless-stopped

  pulsarr:
    image: lakker/pulsarr:latest
    container_name: pulsarr
    ports:
      - 3003:3003
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    env_file:
      - .env
    depends_on:
      - radarr
      - sonarr
    networks:
      - media_net
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./config/gluetun/wg0.conf:/gluetun/wireguard/wg0.conf:ro
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - TZ=Europe/Madrid
      - FIREWALL_OUTBOUND_SUBNETS=172.20.0.0/16
    ports:
      - 9696:9696 # Solo dejamos el puerto de Prowlarr aquí
      - 8191:8191
    networks:
      - media_net
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:gluetun # Prowlarr SÍ pasa por la VPN
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config/prowlarr:/config
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    # Se ha eliminado network_mode y depends_on de gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads
    ports:
      - 8080:8080 # Devolvemos los puertos a qbittorrent
      - 6881:6881
      - 6881:6881/udp
    networks:
      - media_net # Añadimos qbittorrent a la red normal
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: service:gluetun # Ahora sale por la VPN
    depends_on:
    - gluetun
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Madrid
    restart: unless-stopped
      
networks:
  media_net:
    driver: bridge
