[Interface]
# Key for prowlarr
# Bouncing = 1
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = 0Lr8PqP90h1NEsTapx1wgjD3FnndcSLUepiZirwEN2I=
Address = 10.2.0.2/32
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# NL-FREE#116
PublicKey = gE8KNdLXTu9MhSnz6KnMKEYKgmMtd8xZPDq2nC57SyU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 149.34.244.149:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a02:6ea0:c041:2343::10]:51820
PersistentKeepalive = 25